// <auto-generated />
namespace CharterERP.Backend.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CityProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CityProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201506051243256_CityProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
